version: '3.1'
services:
  db:
    image: ubuntu/mysql:latest
    ports:
      - 30306:3306
    environment:
      MYSQL_DATABASE: cuidapet_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql